import fs from "node:fs/promises";

import { base64url } from "jose";
import { decode as cborDecode } from "cbor2";
import {
    validateProofSHA256,
    verifySHA256
} from "@alksol/cfrg-bbs";

import issuerHeaderJSON from "../template/jpt-issuer-header.json" with { type: "json" };
import holderHeaderJSON from "../template/bbs-holder-header.json" with { type: "json" };
import payloadsJSON from "../template/jpt-issuer-payloads.json" with { type: "json" };
import { compactPayloadEncode } from "../utils.mjs";

const disclosedIndexes = new Uint32Array([0, 1, 2, 3]);
async function readJSON(path) {
    return JSON.parse(await fs.readFile(path, "utf-8"));
}

async function readBase64url(path) {
    return base64url.decode(await fs.readFile(path, "utf-8"));
}

function inDir(basePath, fileName) {
    return new URL(fileName, basePath);
}

async function assertKeyStructure(basePath) {
    const privateJwk = await readJSON(inDir(basePath, "bbs-private-key.jwk"));
    const publicJwk = await readJSON(inDir(basePath, "bbs-public-key.jwk"));
    const privateCwk = cborDecode(await fs.readFile(inDir(basePath, "bbs-private-key.cwk")));
    const publicCwk = cborDecode(await fs.readFile(inDir(basePath, "bbs-public-key.cwk")));

    expect(privateJwk.kty).toBe("OKP");
    expect(privateJwk.crv).toBe("BLS12381G2");
    expect(typeof privateJwk.x).toBe("string");
    expect(typeof privateJwk.d).toBe("string");

    expect(publicJwk.kty).toBe("OKP");
    expect(publicJwk.crv).toBe("BLS12381G2");
    expect(typeof publicJwk.x).toBe("string");
    expect(publicJwk.d).toBeUndefined();
    expect(publicJwk.x).toBe(privateJwk.x);

    expect(privateCwk instanceof Map).toBeTrue();
    expect(publicCwk instanceof Map).toBeTrue();
    expect(privateCwk.get(1)).toBe(1);
    expect(privateCwk.get(-1)).toBe(14);
    expect(privateCwk.get(-2) instanceof Uint8Array).toBeTrue();
    expect(privateCwk.get(-4) instanceof Uint8Array).toBeTrue();
    expect(publicCwk.get(1)).toBe(1);
    expect(publicCwk.get(-1)).toBe(14);
    expect(publicCwk.get(-2) instanceof Uint8Array).toBeTrue();
    expect(publicCwk.has(-4)).toBeFalse();
}

async function assertCryptographicVerification(basePath) {
    const publicJwk = await readJSON(inDir(basePath, "bbs-public-key.jwk"));
    const publicKey = base64url.decode(publicJwk.x);

    const issuerCompact = await fs.readFile(inDir(basePath, "bbs-issuer-compact.jwp"), "utf-8");
    const holderCompact = await fs.readFile(inDir(basePath, "bbs-presentation-compact.jwp"), "utf-8");
    const signature = await readBase64url(inDir(basePath, "bbs-issuer-proof.base64url"));
    const proof = await readBase64url(inDir(basePath, "bbs-presentation-proof.base64url"));

    const [issuerHeaderB64, issuerPayloadPart] = issuerCompact.split(".");
    const [holderHeaderB64] = holderCompact.split(".");

    const issuerHeader = base64url.decode(issuerHeaderB64);
    const holderHeader = base64url.decode(holderHeaderB64);
    const payloads = issuerPayloadPart
        .split("~")
        .map((item) => (item === compactPayloadEncode(null) ? null : base64url.decode(item)));
    const disclosedPayloads = payloads.slice(0, 4);

    expect(verifySHA256(publicKey, signature, issuerHeader, payloads)).toBeTrue();
    expect(
        validateProofSHA256(
            publicKey,
            proof,
            issuerHeader,
            holderHeader,
            disclosedPayloads,
            disclosedIndexes
        )
    ).toBeTrue();
}

async function assertCompactMatches(basePath) {
    const issuerCompact = await fs.readFile(inDir(basePath, "bbs-issuer-compact.jwp"), "utf-8");
    const holderCompact = await fs.readFile(inDir(basePath, "bbs-presentation-compact.jwp"), "utf-8");
    const issuerSignature = await readBase64url(inDir(basePath, "bbs-issuer-proof.base64url"));
    const holderProof = await readBase64url(inDir(basePath, "bbs-presentation-proof.base64url"));

    const issuerParts = issuerCompact.split(".");
    const holderParts = holderCompact.split(".");

    expect(issuerParts.length).toBe(3);
    expect(holderParts.length).toBe(4);
    expect(base64url.decode(issuerParts[2])).toEqual(issuerSignature);
    expect(base64url.decode(holderParts[3])).toEqual(holderProof);
}

describe("BBS fixture compatibility", () => {
    it("verifies MATTR legacy vectors with the new library", async () => {
        expect(issuerHeaderJSON).toBeDefined();
        expect(holderHeaderJSON).toBeDefined();
        expect(payloadsJSON.length).toBeGreaterThan(0);
        const legacyPath = new URL("./vectors/bbs/mattr-legacy/", import.meta.url);
        await assertKeyStructure(legacyPath);
        await assertCompactMatches(legacyPath);
        await assertCryptographicVerification(legacyPath);
    });

    it("verifies outputs generated by the migrated scripts", async () => {
        const buildPath = new URL("../build/", import.meta.url);
        await assertKeyStructure(buildPath);
        await assertCompactMatches(buildPath);
        await assertCryptographicVerification(buildPath);
    });
});
