import fs from "node:fs/promises";

import { base64url } from "jose";
import { decode as cborDecode } from "cbor2";
import {
    validateProofSHA256,
    verifySHA256
} from "@alksol/cfrg-bbs";

import protectedHeaderJSON from "../template/jpt-issuer-protected-header.json" with { type: "json" };
import presentationHeaderJSON from "../template/bbs-holder-presentation-header.json" with { type: "json" };
import payloadsJSON from "../template/jpt-issuer-payloads.json" with { type: "json" };

const disclosedIndexes = new Uint32Array([0, 1, 2, 3]);
const protectedHeader = Buffer.from(JSON.stringify(protectedHeaderJSON), "utf-8");
const presentationHeader = Buffer.from(JSON.stringify(presentationHeaderJSON), "utf-8");
const payloads = payloadsJSON.map((item) => Buffer.from(JSON.stringify(item), "utf-8"));
const disclosedPayloads = payloads.slice(0, 4);

async function readJSON(path) {
    return JSON.parse(await fs.readFile(path, "utf-8"));
}

async function readBase64url(path) {
    return base64url.decode(await fs.readFile(path, "utf-8"));
}

function inDir(basePath, fileName) {
    return new URL(fileName, basePath);
}

async function assertKeyStructure(basePath) {
    const privateJwk = await readJSON(inDir(basePath, "private-key.jwk"));
    const publicJwk = await readJSON(inDir(basePath, "public-key.jwk"));
    const privateCwk = cborDecode(await fs.readFile(inDir(basePath, "private-key.cwk")));
    const publicCwk = cborDecode(await fs.readFile(inDir(basePath, "public-key.cwk")));

    expect(privateJwk.kty).toBe("OKP");
    expect(privateJwk.crv).toBe("BLS12381G2");
    expect(typeof privateJwk.x).toBe("string");
    expect(typeof privateJwk.d).toBe("string");

    expect(publicJwk.kty).toBe("OKP");
    expect(publicJwk.crv).toBe("BLS12381G2");
    expect(typeof publicJwk.x).toBe("string");
    expect(publicJwk.d).toBeUndefined();
    expect(publicJwk.x).toBe(privateJwk.x);

    expect(privateCwk instanceof Map).toBeTrue();
    expect(publicCwk instanceof Map).toBeTrue();
    expect(privateCwk.get(1)).toBe(1);
    expect(privateCwk.get(-1)).toBe(14);
    expect(privateCwk.get(-2) instanceof Uint8Array).toBeTrue();
    expect(privateCwk.get(-4) instanceof Uint8Array).toBeTrue();
    expect(publicCwk.get(1)).toBe(1);
    expect(publicCwk.get(-1)).toBe(14);
    expect(publicCwk.get(-2) instanceof Uint8Array).toBeTrue();
    expect(publicCwk.has(-4)).toBeFalse();
}

async function assertCryptographicVerification(basePath) {
    const publicJwk = await readJSON(inDir(basePath, "public-key.jwk"));
    const publicKey = base64url.decode(publicJwk.x);

    const signature = await readBase64url(inDir(basePath, "bbs-issuer-proof.base64url"));
    const proof = await readBase64url(inDir(basePath, "bbs-holder-proof.base64url"));

    expect(verifySHA256(publicKey, signature, protectedHeader, payloads)).toBeTrue();
    expect(
        validateProofSHA256(
            publicKey,
            proof,
            protectedHeader,
            presentationHeader,
            disclosedPayloads,
            disclosedIndexes
        )
    ).toBeTrue();
}

async function assertCompactMatches(basePath) {
    const issuerCompact = await fs.readFile(inDir(basePath, "bbs-issuer.compact.jwp"), "utf-8");
    const holderCompact = await fs.readFile(inDir(basePath, "bbs-holder.compact.jwp"), "utf-8");
    const issuerSignature = await readBase64url(inDir(basePath, "bbs-issuer-proof.base64url"));
    const holderProof = await readBase64url(inDir(basePath, "bbs-holder-proof.base64url"));

    const issuerParts = issuerCompact.split(".");
    const holderParts = holderCompact.split(".");

    expect(issuerParts.length).toBe(3);
    expect(holderParts.length).toBe(4);
    expect(base64url.decode(issuerParts[2])).toEqual(issuerSignature);
    expect(base64url.decode(holderParts[3])).toEqual(holderProof);
}

describe("BBS fixture compatibility", () => {
    it("verifies MATTR legacy vectors with the new library", async () => {
        const legacyPath = new URL("./vectors/bbs/mattr-legacy/", import.meta.url);
        await assertKeyStructure(legacyPath);
        await assertCompactMatches(legacyPath);
        await assertCryptographicVerification(legacyPath);
    });

    it("verifies outputs generated by the migrated scripts", async () => {
        const buildPath = new URL("../build/", import.meta.url);
        await assertKeyStructure(buildPath);
        await assertCompactMatches(buildPath);
        await assertCryptographicVerification(buildPath);
    });
});
